### ISSUE TITLE
IDs in getElementById()/ played audios are the same

### ISSUE THREAD

**Issue by machnicole** [CSTR-Edinburgh/qualtreats#4]
Hi,

I tried to create a mushra test and everything works - except that the individual audio files share the same ID in play_button.html.
In the HTML code on Qualtreats, one can see that the correct (different) audios are linked. But as they share the same ID, only one audio will be played when I click on the play button.
As an example, here is the HTML code for one audio file in Mushra Q1:
```
<html>
<body>
 <audio id="0" src="https://machnicole.github.io/ss_systems/D100\arctic_b0071.wav"></audio>
<div>
    <button onclick="document.getElementById('0').play()">Play</button>
    <button onclick="document.getElementById('0').pause()">Pause</button>
</div>
</body>
</html>
```

And here the HTML code for another audio file in Mushra Q2:
```
<html>
<body>
 <audio id="0" src="https://machnicole.github.io/ss_systems/D100\arctic_b0370.wav"></audio>
<div>
    <button onclick="document.getElementById('0').play()">Play</button>
    <button onclick="document.getElementById('0').pause()">Pause</button>
</div>
</body>
</html>
```
When I click on the play button for the audio file in Mushra Q2, the audio "arctic_b0071.wav" is played, although "arctic_b0370.wav" is linked because they both have the same ID. When I manually change the ID, it works.
The same problem exists for all the references (it's always the same reference that will be played because they all share the same ID "ref").

I attached the output for an example mushra test where I have this problem (it's actually a qsf file, but I had to change the file extension to txt, so that I can upload it into gitub
[output-survey.txt](https://github.com/CSTR-Edinburgh/qualtreats/files/6203122/output-survey.txt)
).
I use Windows and Chrome to create/run the test and for running testmaker.py, I use Python 3.7.

**Comment by jacobjwebber** [comment]
Hi @machnicole 

Thanks for the detailed bug report! Looking at the output survey you uploaded I can't see the same error (must be looking in the wrong place). On lines 197-204 the IDs seem correct. Is this file one that you manually edited?

cc @evelyndjwilliams

**Comment by machnicole** [comment]
Hi @jacobjwebber 

Thanks for the fast reply!
Sorry, I should have specified the lines in the output file. No, it's not the file that I have manually edited, it's the file that gives me that error.
The problem is that the lines 197-204 are correct, but when looking at mushra Q2 in lines 576-585, the IDs are again 0,1, and 2 which means that the audio with ID '0' from Q1 will be played in Q2.
Also in the output qsf file, every reference has ID "ref", which means that always the same reference (the first one with that ID) will be played.

**Comment by jacobjwebber** [comment]
Aaah so all the questions play the same stimuli? It might be fixed if you configure your Qualtrics survey to only show one question per page (then there will be only one audio with a specific id per page).

@evelyndjwilliams do you have any ideas about this? As a long term fix it seems like changing line 120 so that
```
hoice['Display'] = get_play_button(url, str(i + qid*20)) # add audio player as choice
```
the call to get_play_button encodes the QID multiplied by some number larger than the maximum number of stimuli per question is a hack/fix.

**Comment by jacobjwebber** [comment]
so the tl;dr for @machnicole is can you try changing your qualtrics survey so that it displays 1 q per page and let us know if that works? 
In the mean time we'll try and fix this

**Comment by evelyndjwilliams** [comment]
I have fixed this now! Just waiting for Jacob to merge 🙂

**Comment by machnicole** [comment]
Changing my qualtrics survey so that it displays 1 q per page fixed it, thank you!
Also, the changes by @evelyndjwilliams fixed it for the references, when having the questions all on 1 page. Thanks!

**Comment by jacobjwebber** [comment]
Glad to hear. This has now been fixed in main by #6 
Thanks @evelyndjwilliams and @machnicole  for fix/bug report

**Comment by evelyndjwilliams** [comment]
@machnicole this should now be fixed for both reference and test audio 😊

**Comment by jacobjwebber** [comment]
blush Smiling Face with Smiling Eyes Emoji - Emojipediaemo

**Comment by evelyndjwilliams** [comment]
> blush Smiling Face with Smiling Eyes Emoji - Emojipediaemo

https://emojipedia.org/grinning-face-with-sweat/
