### ISSUE TITLE
Should audio player be disabled after playing once for transcription questions by default?

### ISSUE THREAD

**Issue by evelyndjwilliams** [CSTR-Edinburgh/qualtreats#9]
I have added JavaScript to the default template to disable the audio controls for transcription questions after audio is played once.

I don't know if this is preferable as nobody has asked me to add it, but it's how I've been setting up tests.  Maybe unnecessary?

Let me know if I should make a pull request 😊 Smiling Face with Smiling Eyes Emoji

**Comment by dan-wells** [comment]
Great! I agree this is how these tests should be set up, and actually the README already claims this is happening... so this counts as a needed fix

**Comment by jacobjwebber** [comment]
Resolved by #10
